wandb_version: 1

dataset:
  desc: null
  value: samsum
model:
  desc: null
  value: jvelja/t5-samsum
exit_conf_type:
  desc: null
  value: JSD_contrastive_confidence
exit_conf_threshold:
  desc: null
  value: 0.9
exit_min_layer:
  desc: null
  value: 18
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.28.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716135239.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      3:
      - 2
      - 7
      - 16
      - 23
      4: 3.10.12
      5: 0.16.6
      6: 4.28.1
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: eval/rouge1
      5: 1
      6:
      - 1
    - 1: eval/rouge2
      5: 1
      6:
      - 1
    - 1: eval/rougeL
      5: 1
      6:
      - 1
    - 1: eval/rougeLsum
      5: 1
      6:
      - 1
    - 1: eval/gen_len
      5: 1
      6:
      - 1
    - 1: eval/runtime
      5: 1
      6:
      - 1
    - 1: eval/samples_per_second
      5: 1
      6:
      - 1
    - 1: eval/steps_per_second
      5: 1
      6:
      - 1
    - 1: eval/block_avg
      5: 1
      6:
      - 1
    - 1: train/time_encoder_forward
      5: 1
      6:
      - 1
    - 1: train/time_decoder_forward
      5: 1
      6:
      - 1
    - 1: train/time_key_value_gen
      5: 1
      6:
      - 1
    - 1: train/time_attn
      5: 1
      6:
      - 1
    - 1: train/time_ffn
      5: 1
      6:
      - 1
    - 1: train/time_confidence
      5: 1
      6:
      - 1
    - 1: train/time_exit_key_value_gen
      5: 1
      6:
      - 1
    - 1: train/time_exit_attn
      5: 1
      6:
      - 1
    - 1: train/time_exit_ffn
      5: 1
      6:
      - 1
    - 1: train/time_parallel_key_value_gen
      5: 1
      6:
      - 1
    - 1: train/time_parallel_attn
      5: 1
      6:
      - 1
    - 1: train/time_parallel_ffn
      5: 1
      6:
      - 1
    - 1: train/time_estimate_conf
      5: 1
      6:
      - 1
    - 1: train/time_others
      5: 1
      6:
      - 1
vocab_size:
  desc: null
  value: 32128
d_model:
  desc: null
  value: 1024
d_kv:
  desc: null
  value: 64
d_ff:
  desc: null
  value: 4096
num_layers:
  desc: null
  value: 24
num_decoder_layers:
  desc: null
  value: 24
num_heads:
  desc: null
  value: 16
relative_attention_num_buckets:
  desc: null
  value: 32
relative_attention_max_distance:
  desc: null
  value: 128
dropout_rate:
  desc: null
  value: 0.1
layer_norm_epsilon:
  desc: null
  value: 1.0e-06
initializer_factor:
  desc: null
  value: 1.0
feed_forward_proj:
  desc: null
  value: relu
use_cache:
  desc: null
  value: true
dense_act_fn:
  desc: null
  value: relu
is_gated_act:
  desc: null
  value: false
return_dict:
  desc: null
  value: true
output_hidden_states:
  desc: null
  value: false
output_attentions:
  desc: null
  value: false
torchscript:
  desc: null
  value: false
torch_dtype:
  desc: null
  value: float32
use_bfloat16:
  desc: null
  value: false
tf_legacy_loss:
  desc: null
  value: false
pruned_heads:
  desc: null
  value: {}
tie_word_embeddings:
  desc: null
  value: true
is_encoder_decoder:
  desc: null
  value: true
is_decoder:
  desc: null
  value: false
cross_attention_hidden_size:
  desc: null
  value: null
add_cross_attention:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
max_length:
  desc: null
  value: 20
min_length:
  desc: null
  value: 0
do_sample:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
num_beams:
  desc: null
  value: 1
num_beam_groups:
  desc: null
  value: 1
diversity_penalty:
  desc: null
  value: 0.0
temperature:
  desc: null
  value: 1.0
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
typical_p:
  desc: null
  value: 1.0
repetition_penalty:
  desc: null
  value: 1.0
length_penalty:
  desc: null
  value: 1.0
no_repeat_ngram_size:
  desc: null
  value: 0
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
bad_words_ids:
  desc: null
  value: null
num_return_sequences:
  desc: null
  value: 1
chunk_size_feed_forward:
  desc: null
  value: 0
output_scores:
  desc: null
  value: false
return_dict_in_generate:
  desc: null
  value: false
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
remove_invalid_values:
  desc: null
  value: false
exponential_decay_length_penalty:
  desc: null
  value: null
suppress_tokens:
  desc: null
  value: null
begin_suppress_tokens:
  desc: null
  value: null
architectures:
  desc: null
  value:
  - EffT5ForConditionalGeneration
finetuning_task:
  desc: null
  value: null
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
tokenizer_class:
  desc: null
  value: null
prefix:
  desc: null
  value: null
bos_token_id:
  desc: null
  value: null
pad_token_id:
  desc: null
  value: 0
eos_token_id:
  desc: null
  value: 1
sep_token_id:
  desc: null
  value: null
decoder_start_token_id:
  desc: null
  value: 0
task_specific_params:
  desc: null
  value:
    summarization:
      early_stopping: true
      length_penalty: 2.0
      max_length: 200
      min_length: 30
      no_repeat_ngram_size: 3
      num_beams: 4
      prefix: 'summarize: '
    translation_en_to_de:
      early_stopping: true
      max_length: 300
      num_beams: 4
      prefix: 'translate English to German: '
    translation_en_to_fr:
      early_stopping: true
      max_length: 300
      num_beams: 4
      prefix: 'translate English to French: '
    translation_en_to_ro:
      early_stopping: true
      max_length: 300
      num_beams: 4
      prefix: 'translate English to Romanian: '
problem_type:
  desc: null
  value: null
_name_or_path:
  desc: null
  value: jvelja/t5-samsum
transformers_version:
  desc: null
  value: 4.28.1
copy_skipped_hidden_states:
  desc: null
  value: false
distill_layer_alpha:
  desc: null
  value: null
do_layer_transformation:
  desc: null
  value: false
exit_position_temp:
  desc: null
  value: null
intermediate_loss_fn:
  desc: null
  value: null
max_answer_length:
  desc: null
  value: 128
model_type:
  desc: null
  value: t5
n_positions:
  desc: null
  value: 512
output_hidden_states_decoder:
  desc: null
  value: false
output_past:
  desc: null
  value: true
parallel_causal_mask:
  desc: null
  value: true
parallel_gen_token:
  desc: null
  value: true
rollback_conf_threshold:
  desc: null
  value: null
shallow2deep_conf_threshold:
  desc: null
  value: 1.0
shallow2deep_conf_type:
  desc: null
  value: null
shallow_exit_layer:
  desc: null
  value: null
static_exit_layer:
  desc: null
  value: null
train_meta_cm_head:
  desc: null
  value: false
use_early_exit:
  desc: null
  value: true
use_shallow_deep:
  desc: null
  value: false
use_synchronize:
  desc: null
  value: false
type_vocab_reduct:
  desc: null
  value: false
plotting_logits:
  desc: null
  value: false
use_adapt_threshold:
  desc: null
  value: false
use_lora:
  desc: null
  value: false
lora_rank:
  desc: null
  value: 8
lora_alpha:
  desc: null
  value: 8
lora_dropout:
  desc: null
  value: 0.1
lora_target_modules:
  desc: null
  value: null
output_dir:
  desc: null
  value: ./save/jvelja_t5-large/
overwrite_output_dir:
  desc: null
  value: true
do_train:
  desc: null
  value: false
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
evaluation_strategy:
  desc: null
  value: steps
prediction_loss_only:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 8
per_device_eval_batch_size:
  desc: null
  value: 1
per_gpu_train_batch_size:
  desc: null
  value: None
per_gpu_eval_batch_size:
  desc: null
  value: None
gradient_accumulation_steps:
  desc: null
  value: 1
eval_accumulation_steps:
  desc: null
  value: None
eval_delay:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 5.0e-05
weight_decay:
  desc: null
  value: 0.0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
num_train_epochs:
  desc: null
  value: 3.0
max_steps:
  desc: null
  value: -1
lr_scheduler_type:
  desc: null
  value: linear
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: ./save/jvelja_t5-large/runs/May19_16-53-37_MacBook-Pro-di-Matteo-4.local
logging_strategy:
  desc: null
  value: steps
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 500
logging_nan_inf_filter:
  desc: null
  value: true
save_strategy:
  desc: null
  value: steps
save_steps:
  desc: null
  value: 500
save_total_limit:
  desc: null
  value: 1
save_safetensors:
  desc: null
  value: false
save_on_each_node:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: None
jit_mode_eval:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
bf16:
  desc: null
  value: false
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
half_precision_backend:
  desc: null
  value: auto
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: None
local_rank:
  desc: null
  value: -1
xpu_backend:
  desc: null
  value: None
tpu_num_cores:
  desc: null
  value: None
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: '[]'
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: 500
dataloader_num_workers:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: ./save/jvelja_t5-large/
disable_tqdm:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
label_names:
  desc: null
  value: None
load_best_model_at_end:
  desc: null
  value: true
metric_for_best_model:
  desc: null
  value: rougeLsum
greater_is_better:
  desc: null
  value: true
ignore_data_skip:
  desc: null
  value: false
sharded_ddp:
  desc: null
  value: '[]'
fsdp:
  desc: null
  value: '[]'
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_config:
  desc: null
  value: '{''fsdp_min_num_params'': 0, ''xla'': False, ''xla_fsdp_grad_ckpt'': False}'
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: None
deepspeed:
  desc: null
  value: None
label_smoothing_factor:
  desc: null
  value: 0.0
optim:
  desc: null
  value: adafactor
optim_args:
  desc: null
  value: None
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
report_to:
  desc: null
  value: '[''wandb'']'
ddp_find_unused_parameters:
  desc: null
  value: None
ddp_bucket_cap_mb:
  desc: null
  value: None
dataloader_pin_memory:
  desc: null
  value: true
skip_memory_metrics:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: None
hub_model_id:
  desc: null
  value: None
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
hub_private_repo:
  desc: null
  value: false
gradient_checkpointing:
  desc: null
  value: false
include_inputs_for_metrics:
  desc: null
  value: true
fp16_backend:
  desc: null
  value: auto
push_to_hub_model_id:
  desc: null
  value: None
push_to_hub_organization:
  desc: null
  value: None
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
mp_parameters:
  desc: null
  value: ''
auto_find_batch_size:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
torchdynamo:
  desc: null
  value: None
ray_scope:
  desc: null
  value: last
ddp_timeout:
  desc: null
  value: 1800
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: None
torch_compile_mode:
  desc: null
  value: None
sortish_sampler:
  desc: null
  value: false
predict_with_generate:
  desc: null
  value: true
generation_max_length:
  desc: null
  value: 128
generation_num_beams:
  desc: null
  value: None
generation_config:
  desc: null
  value: None
train_batch_size:
  desc: null
  value: 8
eval_batch_size:
  desc: null
  value: 1
